files:
  include: 'src/scss/**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 1
  no-color-literals: 1
  no-combinators: 0
  no-css-comments: 0
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 1
  no-ids: 2
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 1
  property-units: 0

  # Nesting
  declarations-before-nesting: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 2

  # Name Formats
  class-name-format: 0
  function-name-format: 0
  id-name-format: 0
  mixin-name-format: 0
  placeholder-name-format: 0
  variable-name-format: 0

  # Style Guide
  attribute-quotes: 1
  bem-depth: 0
  border-zero: 2
  brace-style: 2
  clean-import-paths: 0
  empty-args: 0
  hex-length: 2
  hex-notation: 2
  indentation: 2
  leading-zero: 2
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth: 0
  property-sort-order: 2
  pseudo-element: 0
  quotes: 2
  shorthand-values: 0
  url-quotes: 2
  variable-for-property:
    - 2
    -
      include: true
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 0
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
